on:
  push:
    branches: [ master ]

jobs:
  # https://stackoverflow.com/a/71489231
  tests:
    runs-on: ubuntu-latest
    uses: tests.yml  # use the callable tests job to run tests
  deploy:
    name: deploy
    needs: [tests]  # require tests to pass before deploy runs
    runs-on: ubuntu-latest
    steps:
    - name: Push
      run: dotnet nuget push CorporateEspionage.${VERSION}.nupkg --source https://nuget.repo.corsac.nl/v3/index.json --api-key ${{ secrets.PUSH_KEY }}
