on:
  push:
    branches: [ master ]

jobs:
  # https://stackoverflow.com/a/71489231
  tests:
    uses: ./.github/workflows/tests.yml  # use the callable tests job to run tests
  deploy:
    name: deploy
    needs: [tests]  # require tests to pass before deploy runs
    runs-on: ubuntu-latest
    steps:
    - name: Set VERSION variable from tag
      run: echo "VERSION=$(git tag | head -n 1)" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # needed to get tags
        fetch-depth: 0
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push CorporateEspionage.${VERSION}.nupkg --source https://nuget.repo.corsac.nl/v3/index.json --api-key ${{ secrets.PUSH_KEY }}
